# This rule is not used by the project wish-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to wishlist.k8s.lex.la resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wish-operator
    app.kubernetes.io/managed-by: kustomize
  name: wish-viewer-role
rules:
- apiGroups:
  - wishlist.k8s.lex.la
  resources:
  - wishes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wishlist.k8s.lex.la
  resources:
  - wishes/status
  verbs:
  - get
