apiVersion: v2
name: wish-operator
description: Kubernetes operator for managing wishlists
type: application
version: 0.3.1
appVersion: "0.3.1"
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
