name: Test Helm

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm (latest)
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Helm version
        run: helm version

      - name: Helm plugin install help
        run: helm plugin install --help
